Rails/week-1/hacker_news/config/routes.rb
Rails.application.routes.draw do
  root :to => 'links#index'

  resources :links do
    resources :comments, :except => [:show, :index]
  end
end

Rails/week-1/hacker_news/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link

  validates :content, :presence => true
end

Rails/week-1/hacker_news/app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments

  validates :name, :presence => true
  validates :url, :presence => true
end

Rails/week-1/hacker_news/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @link = Link.find(params[:link_id])
    @comment = Comment.new
  end

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    if @comment.save
      flash[:message] = 'Comment Posted'
      redirect_to link_path(@link)
    else
      flash[:error] = 'Error: Invalid Entry!'
      render :new
    end
  end

private
  def comment_params
    params.require(:comment).permit(:content, :username)
  end
end

Rails/week-1/hacker_news/app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if params[:sortby]
      if params[:sortby] == 'hot'
        @links = Link.order(:upvotes => :desc)
      elsif params[:sortby] == 'latest'
        @links = Link.order(:created_at => :desc)
      elsif params[:sortby] == 'trending'
        @links = Link.order(:upvotes => :desc, :created_at => :desc)
      end
    else
      @links = Link.order(:upvotes => :desc)
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = 'List successfully added!'
      redirect_to link_path(@link)
    else
      flash[:error] = 'Error: Invalid Entry!'
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    p link_params
    @link = Link.find(params[:id])
    if @link.update(link_params)
      flash[:notice] = 'List successfully updated!'
      redirect_to links_path
    else
      flash[:error] = 'Error: Invalid Entry!'
      render :edit
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:notice] = 'List successfully deleted!'
    redirect_to links_path
  end

private
  def link_params
    params.require(:link).permit(:name, :url, :username, :upvotes)
  end
end

Rails/week-1/hacker_news/app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <%= f.submit %>
<% end %>

Rails/week-1/hacker_news/app/views/links/edit.html.erb
<h3>Edit Link</h3>

<%= render 'form' %>

Rails/week-1/hacker_news/app/views/links/index.html.erb
<p>
  <%= link_to 'Hot', links_path(:sortby => 'hot') %> |
  <%= link_to 'Latest', links_path(:sortby => 'latest') %> |
  <%= link_to 'Trending', links_path(:sortby => 'trending') %> |
  <%= link_to 'New', new_link_path %>
</p>
<ul>
  <% @links.each do |link| %>
    <li>
      <%= form_for link do |f| %>
        <%= f.hidden_field :upvotes, :value => link.upvotes + 1 %>
        <%= f.button'<i class="fa fa-angle-up" aria-hidden="true"></i>'.html_safe,  class: 'circle-button' %>
      <% end %>
      <%= "(#{link.upvotes})" %>
      <%= link_to link.name, link.url %>
      <%= link_to 'Comments', link_path(link) %>
    </li>
  <% end %>
</ul>

Rails/week-1/hacker_news/app/views/links/new.html.erb
<h3>Add Link</h3>

<%= render 'form' %>

Rails/week-1/hacker_news/app/views/links/show.html.erb
<p>
  <%= link_to 'Add a Comment', new_link_comment_path(@link) %> |
  <%= link_to 'Edit', edit_link_path(@link) %> |
  <%= link_to 'Delete', link_path(@link),
              :data => {:confirm => 'Are you sure?', :method => 'delete'} %> |
  <%= link_to 'Links', links_path %>
</p>

<h1><%= @link.name %></h1>
<h4>URL: <%= @link.url %></h4>
<h4>Author: <%= @link.username %></h4>

<% if @link.comments.any? %>
  <h4>Comments:</h4>

  <ul>
    <% @link.comments.each do |comment| %>
      <%= comment.content %> - <% comment.username %>
      <%= link_to 'Edit', edit_link_comment_path(@link, comment) %>
      <%= link_to 'Delete', link_comment_path(@link, comment), :data => {
          confirm: 'Are you sure?',
          method: 'delete'
      } %>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments yet.</p>
<% end %>