Rails/week-1/gummi_bear_kingdom/config/routes.rb
Rails.application.routes.draw do
  root :to => 'welcome#index'

  resources :products
end

Rails/week-1/gummi_bear_kingdom/app/models/product.rb
class Product < ApplicationRecord
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :origin, :presence => true
end

Rails/week-1/gummi_bear_kingdom/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    p @products

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params.except(:imagedata) )
    respond_to do |format|
      if @product.save
        save_product
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params.except(:imagedata))
        save_product
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def generate_file_name
      parts = params[:product][:imagedata].original_filename.split(".")
      "#{parts[0]}-#{Time.now.nsec}.#{parts[1]}"
    end

    def save_product
      if params[:product].key?(:imagedata)
        uploaded_io = params[:product][:imagedata]
        File.open(Rails.root.join('public', 'uploads', params[:product][:image]), 'wb') do |file|
          file.write(uploaded_io.read)
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      if params[:product].key?(:imagedata)
        params[:product][:image] = generate_file_name
      end
      params.require(:product).permit(:name, :cost, :origin, :image, :imagedata)
    end
end

Rails/week-1/gummi_bear_kingdom/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.all
  end
end

Rails/week-1/gummi_bear_kingdom/app/helpers/products_helper.rb
module ProductsHelper
end

Rails/week-1/gummi_bear_kingdom/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Gummy Bear Kingdom</a>
    </div>
    <p class="navbar-text navbar-right">
      <a href="/products" class="navbar-link">Products</a>
    </p>
  </div>
</nav>

Rails/week-1/gummi_bear_kingdom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GummiBearKingdom</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  <footer>
    <!--<a href="http://www.freepik.com">Designed by Terdpongvector / Freepik</a>-->
  </footer>

</body>
</html>

Rails/week-1/gummi_bear_kingdom/app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-horizontal center">
      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :cost %>
        <%= f.text_field :cost, :class => 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :origin %>
        <%= f.text_field :origin, :class => 'form-control' %>
      </div>

      <div class="field form-group">
        <%= f.label :imagedata %>
        <%= f.file_field :imagedata, :class => 'form-control' %>
      </div>

      <div class="actions form-group">
        <%= f.submit %>
      </div>
    </div>
<% end %>

Rails/week-1/gummi_bear_kingdom/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

Rails/week-1/gummi_bear_kingdom/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="products">
  <% @products.each do |product| %>
    <%= link_to product_path(product) do %>
          <img src="/uploads/<%= product.image %>" alt="" style="max-width: 125px; max-height: 125px">
    <% end %>
  <% end %>
</div>
<%= link_to 'New Product', new_product_path %>

Rails/week-1/gummi_bear_kingdom/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

Rails/week-1/gummi_bear_kingdom/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="purple text-center"><%= @product.name %></h1>
<div class="text-center">
  <img src="/uploads/<%= @product.image %>" alt="" style="max-width: 400px; max-height: 400px;">
</div>
<div class="text-center">
  <p>
    <strong>Cost:</strong>
    <%= @product.cost %>
  </p>

  <p>
    <strong>Origin:</strong>
    <%= @product.origin %>
  </p>


  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Delete', product_path(@product),
              :data => {:confirm => 'Are you sure?', :method => 'delete'} %> |
  <%= link_to 'Back', products_path %>
</div>