Rails/week-1/to_do_rails/config/routes.rb
Rails.application.routes.draw do
  root :to => 'lists#index'

  resources :lists do
    resources :tasks, :except => [:show, :index]
  end
end

Rails/week-1/to_do_rails/app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks

  validates :name, :presence => true
end

Rails/week-1/to_do_rails/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true
end

Rails/week-1/to_do_rails/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = 'List successfully added!'
      redirect_to list_path(@list)
    else
      flash[:alert] = 'Invalid Entry.'
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    flash[:notice] = 'List successfully updated.'
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      flash[:alert] = 'Invalid Entry.'
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash[:notice] = 'List successfully deleted.'
    redirect_to lists_path
  end

private
  def list_params
    params.require(:list).permit(:name)
  end
end

Rails/week-1/to_do_rails/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to list_path(@task.list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(@list)
  end

private
  def task_params
    params.require(:task).permit(:description)
  end
end

Rails/week-1/to_do_rails/app/views/lists/_form.html.erb
<%= render 'layouts/errors', :object => @list %>

<%= form_for @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

Rails/week-1/to_do_rails/app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render 'form' %>

Rails/week-1/to_do_rails/app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
      <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<hr>

<%= link_to 'New List', new_list_path %>

Rails/week-1/to_do_rails/app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

Rails/week-1/to_do_rails/app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<% if @list.tasks.any? %>
    <h4>Here are the tasks for this list:</h4>
    <ul>
      <% @list.tasks.each do |task| %>
        <li>
          <%= task.description %>
          <%= link_to 'Edit', edit_list_task_path(@list, task) %>
          <%= link_to 'Delete', list_task_path(@list, task),
                      :data => {:confirm => 'Are you sure?',
                                :method => 'delete'}%>
        </li>
      <% end %>
    </ul>
<% else %>
    <p>There are no tasks yet!</p>
<% end %>

<p><%= link_to 'Add a task', new_list_task_path(@list) %></p>
<p><%= link_to 'Edit', edit_list_path(@list) %></p>
<p><%= link_to 'Delete', list_path(@list),
               :data => {:confirm => 'Are you sure?', :method => 'delete'} %></p>

<hr>
<p><%= link_to 'Return to lists', lists_path %></p>